//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int AdID { get; set; }
        public int UserID { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string City { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public int Id_Status { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
    
        public virtual User User { get; set; }
        public virtual Status Status { get; set; }
    }
}
